name: Deploy FastAPI to Hugging Face Space

on:
  push:
    branches: [ "logic_improve_branch" ] 
    paths:
      - 'Logic_Server/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # הגדרת משתמש וירטואלי כדי ש-Git לא יזרוק שגיאות
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # חיבור השרת
          git remote add hf https://idohaver7:$HF_TOKEN@huggingface.co/spaces/idohaver7/patrolvision
          
          # חיתוך התיקייה בלבד לתוך ענף זמני שנקרא deploy_branch
          git subtree split --prefix Model_Server -b deploy_branch
          
          # דחיפה אגרסיבית (Force) ל-Hugging Face שדורסת את ההיסטוריה הישנה שם
          git push hf deploy_branch:main --force